version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.4.0
  aws-ecs: circleci/aws-ecs@2.0
jobs:
  build-save-image:
    working_directory: ~/project/DAI/Data Web Service
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest"' >> $BASH_ENV
      - run:
          name: Install dependencies for project
          command: mvn install
      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Build image
          command: |
            docker build -t ${FULL_IMAGE_NAME} .
      - run:
          name: Push image
          command: |
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push ${FULL_IMAGE_NAME}

workflows:
  build-save-image-wf:
    jobs:
      - build-save-image
  deploy-wf:
    jobs:
      - aws-ecs/deploy-service-update:
          cluster-name: 'sep4-cluster'
          container-image-name-updates: 'image=931417283309.dkr.ecr.eu-central-1.amazonaws.com/sep4-data-service'
          family: 'sep4-task-definition'
          requires:
            - build-save-image-wf